- hosts: all
  tasks :
     - name : "DeployVM"
       proxmox_kvm:
          api_user     : root@pam
          api_password : Prox2020
          api_host     : 192.168.31.128
          name         : test1
          node         : prox13
          state        : started

     - name : "DeployVM"
       proxmox_kvm:
          api_user     : root@pam
          api_password : Prox2020
          api_host     : 192.168.31.130
          name         : test2
          node         : Prox13
          state        : started

     - name : "DeployVM"
       proxmox_kvm:
          api_user     : root@pam
          api_password : Prox2020
          api_host     : 192.168.31.130
          name         : test3
          node         : Prox-13
          state        : started

